  [[global]]
    name = "Docs"
    weight = 1
    identifier = "docs"
    url = "/documentation/"

  [[global]]
    name = "News"
    weight = 5
    identifier = "news"
    url = "/news/"

  # Anything with a weight > 100 gets an external icon
  [[global]]
    name = "Community"
    weight = 10
    icon = true
    identifier = "community"
    post = "external"
    url = "https://gitter.im/ocfcloud/Lobby/"

  [[global]]
    name = "Try LIVE"
    weight = 20
    icon = true
    identifier = "themes"
    post = "external"
    url = "https://try.plgd.cloud"